
project_id = "sheslhegcubntqohlgts"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[[functions]]
name = "create-checkout-session"
verify_jwt = false

[[functions]]
name = "stripe-webhook"
verify_jwt = false
